[DEN-168] added custom fields to adjustments
recurly/recurly-client-ruby pull request #818
Opened 2023-01-12 23:24 UTC by jorge

2023-01-17 14:40 UTC, douglaslise approved these changes

2023-01-17 15:23 UTC, mwlang commented on spec/fixtures/adjustments/show-200.xml
> +      <value>priceless</value>
**suggestion**:  Let's be consistent with examples.  `field1` vs. `thing1`

2023-01-17 15:26 UTC, mwlang requested changes
Remove internal ticket references from PR description/title.  Perhaps consider a more meaningful example such as size/large vs. field1/priceless -- at the very least be consistent with examples

2023-01-19 12:46 UTC, mwlang approved these changes

2023-01-19 16:07 UTC, merged