Update client library to support `CustomFieldDefinition`
recurly/recurly-client-ruby pull request #824
Opened 2023-01-30 13:21 UTC by lsfernandes92

This PR aims to:
* Adds `CustomFieldDefinition` model
* Adds `GET v2/custom_field_definitions` endpoint to this client library
* Adds `GET v2/custom_field_definitions/:custom_field_definition_id` endpoint to this client library
* Adds `GET v2/custom_field_definitions?related_type=plan` endpoint to this client library

Sample code request for the listing:
```ruby
Recurly::CustomFieldDefinition.find_each do |definition|
  puts "Custom Field Definition: #{definition}"
end
```

Sample code request for the getting:
```ruby
definition = Recurly::CustomFieldDefinition.find(<DEFINITION_ID>)
puts "Custom Field Definition: ", definition
```

Sample code request for the filtered listing:
```ruby
Recurly::CustomFieldDefinition.all(related_type: <RELATED_TYPE>).each do |definition|
   puts "Custom Field Definition: #{definition}"
end
```

2023-01-30 18:48 UTC, btruncali1 approved these changes

2023-01-31 14:48 UTC, mwlang requested changes

2023-01-31 14:48 UTC, mwlang commented on lib/recurly/custom_field_definition.rb
> +    # alias to_param plan_code
remove comment.

2023-01-31 15:21 UTC, mwlang approved these changes

2023-01-31 16:46 UTC, merged